### Send POST request with json body
POST http://localhost:8081/performAction
Content-Type: application/json

{
  "action": "WORRYHEALTH"
}

### Send POST request with json body
POST http://localhost:8081/performAction
Content-Type: application/json

{
  "action": "TEMPACTION"
}

### Send POST request with json body
POST http://localhost:8081/getAttribute
Content-Type: application/json

{
  "class": "feeling",
  "type": "staminaWorry"
}

### GET request with a header
GET http://localhost:8081/getActions