### label start: answer 1
POST http://localhost:8081/performAction
Content-Type: application/json

{
  "action": "INCREASE_HEALTH_WORRY"
}

### label start: answer 2
POST http://localhost:8081/performAction
Content-Type: application/json

{
  "action": "INCREASE_STAMINA_WORRY"
}

### label start: answer 3
POST http://localhost:8081/performAction
Content-Type: application/json

{
  "action": "INCREASE_HEALTH_WORRY"
}

### getAttribute
POST http://localhost:8081/getAttribute
Content-Type: application/json

{
  "class": "feeling",
  "type": "staminaWorry"
}

### getAttribute
POST http://localhost:8081/getAttribute
Content-Type: application/json

{
  "class": "feeling",
  "type": "healthWorry"
}

### label start: get transition action
GET http://localhost:8081/getActions

### run triggers
GET http://localhost:8081/runTriggers

### getAttribute
POST http://localhost:8081/getAttribute
Content-Type: application/json

{
  "class": "attribute",
  "type": "health"
}

### getAttribute
POST http://localhost:8081/getAttribute
Content-Type: application/json

{
  "class": "attribute",
  "type": "stamina"
}

### label start: get transition action
GET http://localhost:8081/getActions


